name: Dependency Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Dependency Check
        run: npm install -g @cyclonedx/bom && cyclonedx-bom -o bom.xml

      - name: Archive Dependency Check Report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-report
          path: bom.xml
